/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.transport;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RecordVehicles extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7661434091935712036L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecordVehicles\",\"namespace\":\"nlmk.l3.transport\",\"fields\":[{\"name\":\"vehicleNum\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Номер средства транспортировки\"},{\"name\":\"weightNet\",\"type\":\"float\",\"doc\":\"Вес ресурса\"},{\"name\":\"waybillNum\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Номер накладной\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RecordVehicles> ENCODER =
      new BinaryMessageEncoder<RecordVehicles>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RecordVehicles> DECODER =
      new BinaryMessageDecoder<RecordVehicles>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RecordVehicles> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RecordVehicles> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RecordVehicles> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RecordVehicles>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RecordVehicles to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RecordVehicles from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RecordVehicles instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RecordVehicles fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Номер средства транспортировки */
   private java.lang.String vehicleNum;
  /** Вес ресурса */
   private float weightNet;
  /** Номер накладной */
   private java.lang.String waybillNum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecordVehicles() {}

  /**
   * All-args constructor.
   * @param vehicleNum Номер средства транспортировки
   * @param weightNet Вес ресурса
   * @param waybillNum Номер накладной
   */
  public RecordVehicles(java.lang.String vehicleNum, java.lang.Float weightNet, java.lang.String waybillNum) {
    this.vehicleNum = vehicleNum;
    this.weightNet = weightNet;
    this.waybillNum = waybillNum;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return vehicleNum;
    case 1: return weightNet;
    case 2: return waybillNum;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: vehicleNum = value$ != null ? value$.toString() : null; break;
    case 1: weightNet = (java.lang.Float)value$; break;
    case 2: waybillNum = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'vehicleNum' field.
   * @return Номер средства транспортировки
   */
  public java.lang.String getVehicleNum() {
    return vehicleNum;
  }


  /**
   * Sets the value of the 'vehicleNum' field.
   * Номер средства транспортировки
   * @param value the value to set.
   */
  public void setVehicleNum(java.lang.String value) {
    this.vehicleNum = value;
  }

  /**
   * Gets the value of the 'weightNet' field.
   * @return Вес ресурса
   */
  public float getWeightNet() {
    return weightNet;
  }


  /**
   * Sets the value of the 'weightNet' field.
   * Вес ресурса
   * @param value the value to set.
   */
  public void setWeightNet(float value) {
    this.weightNet = value;
  }

  /**
   * Gets the value of the 'waybillNum' field.
   * @return Номер накладной
   */
  public java.lang.String getWaybillNum() {
    return waybillNum;
  }


  /**
   * Sets the value of the 'waybillNum' field.
   * Номер накладной
   * @param value the value to set.
   */
  public void setWaybillNum(java.lang.String value) {
    this.waybillNum = value;
  }

  /**
   * Creates a new RecordVehicles RecordBuilder.
   * @return A new RecordVehicles RecordBuilder
   */
  public static nlmk.l3.transport.RecordVehicles.Builder newBuilder() {
    return new nlmk.l3.transport.RecordVehicles.Builder();
  }

  /**
   * Creates a new RecordVehicles RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecordVehicles RecordBuilder
   */
  public static nlmk.l3.transport.RecordVehicles.Builder newBuilder(nlmk.l3.transport.RecordVehicles.Builder other) {
    if (other == null) {
      return new nlmk.l3.transport.RecordVehicles.Builder();
    } else {
      return new nlmk.l3.transport.RecordVehicles.Builder(other);
    }
  }

  /**
   * Creates a new RecordVehicles RecordBuilder by copying an existing RecordVehicles instance.
   * @param other The existing instance to copy.
   * @return A new RecordVehicles RecordBuilder
   */
  public static nlmk.l3.transport.RecordVehicles.Builder newBuilder(nlmk.l3.transport.RecordVehicles other) {
    if (other == null) {
      return new nlmk.l3.transport.RecordVehicles.Builder();
    } else {
      return new nlmk.l3.transport.RecordVehicles.Builder(other);
    }
  }

  /**
   * RecordBuilder for RecordVehicles instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecordVehicles>
    implements org.apache.avro.data.RecordBuilder<RecordVehicles> {

    /** Номер средства транспортировки */
    private java.lang.String vehicleNum;
    /** Вес ресурса */
    private float weightNet;
    /** Номер накладной */
    private java.lang.String waybillNum;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.l3.transport.RecordVehicles.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.vehicleNum)) {
        this.vehicleNum = data().deepCopy(fields()[0].schema(), other.vehicleNum);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.weightNet)) {
        this.weightNet = data().deepCopy(fields()[1].schema(), other.weightNet);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.waybillNum)) {
        this.waybillNum = data().deepCopy(fields()[2].schema(), other.waybillNum);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RecordVehicles instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.l3.transport.RecordVehicles other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.vehicleNum)) {
        this.vehicleNum = data().deepCopy(fields()[0].schema(), other.vehicleNum);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.weightNet)) {
        this.weightNet = data().deepCopy(fields()[1].schema(), other.weightNet);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.waybillNum)) {
        this.waybillNum = data().deepCopy(fields()[2].schema(), other.waybillNum);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'vehicleNum' field.
      * Номер средства транспортировки
      * @return The value.
      */
    public java.lang.String getVehicleNum() {
      return vehicleNum;
    }


    /**
      * Sets the value of the 'vehicleNum' field.
      * Номер средства транспортировки
      * @param value The value of 'vehicleNum'.
      * @return This builder.
      */
    public nlmk.l3.transport.RecordVehicles.Builder setVehicleNum(java.lang.String value) {
      validate(fields()[0], value);
      this.vehicleNum = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'vehicleNum' field has been set.
      * Номер средства транспортировки
      * @return True if the 'vehicleNum' field has been set, false otherwise.
      */
    public boolean hasVehicleNum() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'vehicleNum' field.
      * Номер средства транспортировки
      * @return This builder.
      */
    public nlmk.l3.transport.RecordVehicles.Builder clearVehicleNum() {
      vehicleNum = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'weightNet' field.
      * Вес ресурса
      * @return The value.
      */
    public float getWeightNet() {
      return weightNet;
    }


    /**
      * Sets the value of the 'weightNet' field.
      * Вес ресурса
      * @param value The value of 'weightNet'.
      * @return This builder.
      */
    public nlmk.l3.transport.RecordVehicles.Builder setWeightNet(float value) {
      validate(fields()[1], value);
      this.weightNet = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'weightNet' field has been set.
      * Вес ресурса
      * @return True if the 'weightNet' field has been set, false otherwise.
      */
    public boolean hasWeightNet() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'weightNet' field.
      * Вес ресурса
      * @return This builder.
      */
    public nlmk.l3.transport.RecordVehicles.Builder clearWeightNet() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'waybillNum' field.
      * Номер накладной
      * @return The value.
      */
    public java.lang.String getWaybillNum() {
      return waybillNum;
    }


    /**
      * Sets the value of the 'waybillNum' field.
      * Номер накладной
      * @param value The value of 'waybillNum'.
      * @return This builder.
      */
    public nlmk.l3.transport.RecordVehicles.Builder setWaybillNum(java.lang.String value) {
      validate(fields()[2], value);
      this.waybillNum = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'waybillNum' field has been set.
      * Номер накладной
      * @return True if the 'waybillNum' field has been set, false otherwise.
      */
    public boolean hasWaybillNum() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'waybillNum' field.
      * Номер накладной
      * @return This builder.
      */
    public nlmk.l3.transport.RecordVehicles.Builder clearWaybillNum() {
      waybillNum = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RecordVehicles build() {
      try {
        RecordVehicles record = new RecordVehicles();
        record.vehicleNum = fieldSetFlags()[0] ? this.vehicleNum : (java.lang.String) defaultValue(fields()[0]);
        record.weightNet = fieldSetFlags()[1] ? this.weightNet : (java.lang.Float) defaultValue(fields()[1]);
        record.waybillNum = fieldSetFlags()[2] ? this.waybillNum : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RecordVehicles>
    WRITER$ = (org.apache.avro.io.DatumWriter<RecordVehicles>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RecordVehicles>
    READER$ = (org.apache.avro.io.DatumReader<RecordVehicles>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.vehicleNum);

    out.writeFloat(this.weightNet);

    if (this.waybillNum == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.waybillNum);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.vehicleNum = in.readString();

      this.weightNet = in.readFloat();

      if (in.readIndex() != 1) {
        in.readNull();
        this.waybillNum = null;
      } else {
        this.waybillNum = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.vehicleNum = in.readString();
          break;

        case 1:
          this.weightNet = in.readFloat();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.waybillNum = null;
          } else {
            this.waybillNum = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










