/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.transport.weighing;
@org.apache.avro.specific.AvroGenerated
public enum enum_op implements org.apache.avro.generic.GenericEnumSymbol<enum_op> {
  I, U, D  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"enum_op\",\"namespace\":\"nlmk.l3.transport.weighing\",\"symbols\":[\"I\",\"U\",\"D\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
