/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package nlmk.l3.transport.far_arrival;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RecordPk extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6841988205289326038L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecordPk\",\"namespace\":\"nlmk.l3.transport.far_arrival\",\"fields\":[{\"name\":\"waybillNum\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Номер накладной\"},{\"name\":\"departureDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RecordPk> ENCODER =
      new BinaryMessageEncoder<RecordPk>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RecordPk> DECODER =
      new BinaryMessageDecoder<RecordPk>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RecordPk> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RecordPk> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RecordPk> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RecordPk>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RecordPk to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RecordPk from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RecordPk instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RecordPk fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Номер накладной */
  private java.lang.CharSequence waybillNum;
  /** Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm) */
  private java.lang.CharSequence departureDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecordPk() {}

  /**
   * All-args constructor.
   * @param waybillNum Номер накладной
   * @param departureDate Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
   */
  public RecordPk(java.lang.CharSequence waybillNum, java.lang.CharSequence departureDate) {
    this.waybillNum = waybillNum;
    this.departureDate = departureDate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return waybillNum;
    case 1: return departureDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: waybillNum = (java.lang.CharSequence)value$; break;
    case 1: departureDate = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'waybillNum' field.
   * @return Номер накладной
   */
  public java.lang.CharSequence getWaybillNum() {
    return waybillNum;
  }


  /**
   * Sets the value of the 'waybillNum' field.
   * Номер накладной
   * @param value the value to set.
   */
  public void setWaybillNum(java.lang.CharSequence value) {
    this.waybillNum = value;
  }

  /**
   * Gets the value of the 'departureDate' field.
   * @return Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
   */
  public java.lang.CharSequence getDepartureDate() {
    return departureDate;
  }


  /**
   * Sets the value of the 'departureDate' field.
   * Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
   * @param value the value to set.
   */
  public void setDepartureDate(java.lang.CharSequence value) {
    this.departureDate = value;
  }

  /**
   * Creates a new RecordPk RecordBuilder.
   * @return A new RecordPk RecordBuilder
   */
  public static nlmk.l3.transport.far_arrival.RecordPk.Builder newBuilder() {
    return new nlmk.l3.transport.far_arrival.RecordPk.Builder();
  }

  /**
   * Creates a new RecordPk RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecordPk RecordBuilder
   */
  public static nlmk.l3.transport.far_arrival.RecordPk.Builder newBuilder(nlmk.l3.transport.far_arrival.RecordPk.Builder other) {
    if (other == null) {
      return new nlmk.l3.transport.far_arrival.RecordPk.Builder();
    } else {
      return new nlmk.l3.transport.far_arrival.RecordPk.Builder(other);
    }
  }

  /**
   * Creates a new RecordPk RecordBuilder by copying an existing RecordPk instance.
   * @param other The existing instance to copy.
   * @return A new RecordPk RecordBuilder
   */
  public static nlmk.l3.transport.far_arrival.RecordPk.Builder newBuilder(nlmk.l3.transport.far_arrival.RecordPk other) {
    if (other == null) {
      return new nlmk.l3.transport.far_arrival.RecordPk.Builder();
    } else {
      return new nlmk.l3.transport.far_arrival.RecordPk.Builder(other);
    }
  }

  /**
   * RecordBuilder for RecordPk instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecordPk>
    implements org.apache.avro.data.RecordBuilder<RecordPk> {

    /** Номер накладной */
    private java.lang.CharSequence waybillNum;
    /** Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm) */
    private java.lang.CharSequence departureDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(nlmk.l3.transport.far_arrival.RecordPk.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.waybillNum)) {
        this.waybillNum = data().deepCopy(fields()[0].schema(), other.waybillNum);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.departureDate)) {
        this.departureDate = data().deepCopy(fields()[1].schema(), other.departureDate);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RecordPk instance
     * @param other The existing instance to copy.
     */
    private Builder(nlmk.l3.transport.far_arrival.RecordPk other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.waybillNum)) {
        this.waybillNum = data().deepCopy(fields()[0].schema(), other.waybillNum);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.departureDate)) {
        this.departureDate = data().deepCopy(fields()[1].schema(), other.departureDate);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'waybillNum' field.
      * Номер накладной
      * @return The value.
      */
    public java.lang.CharSequence getWaybillNum() {
      return waybillNum;
    }


    /**
      * Sets the value of the 'waybillNum' field.
      * Номер накладной
      * @param value The value of 'waybillNum'.
      * @return This builder.
      */
    public nlmk.l3.transport.far_arrival.RecordPk.Builder setWaybillNum(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.waybillNum = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'waybillNum' field has been set.
      * Номер накладной
      * @return True if the 'waybillNum' field has been set, false otherwise.
      */
    public boolean hasWaybillNum() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'waybillNum' field.
      * Номер накладной
      * @return This builder.
      */
    public nlmk.l3.transport.far_arrival.RecordPk.Builder clearWaybillNum() {
      waybillNum = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'departureDate' field.
      * Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
      * @return The value.
      */
    public java.lang.CharSequence getDepartureDate() {
      return departureDate;
    }


    /**
      * Sets the value of the 'departureDate' field.
      * Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
      * @param value The value of 'departureDate'.
      * @return This builder.
      */
    public nlmk.l3.transport.far_arrival.RecordPk.Builder setDepartureDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.departureDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'departureDate' field has been set.
      * Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
      * @return True if the 'departureDate' field has been set, false otherwise.
      */
    public boolean hasDepartureDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'departureDate' field.
      * Дата отправления (в формате YYYY-MM-DDThh:mm:ss+hh:mm)
      * @return This builder.
      */
    public nlmk.l3.transport.far_arrival.RecordPk.Builder clearDepartureDate() {
      departureDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RecordPk build() {
      try {
        RecordPk record = new RecordPk();
        record.waybillNum = fieldSetFlags()[0] ? this.waybillNum : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.departureDate = fieldSetFlags()[1] ? this.departureDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RecordPk>
    WRITER$ = (org.apache.avro.io.DatumWriter<RecordPk>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RecordPk>
    READER$ = (org.apache.avro.io.DatumReader<RecordPk>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.waybillNum);

    out.writeString(this.departureDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.waybillNum = in.readString(this.waybillNum instanceof Utf8 ? (Utf8)this.waybillNum : null);

      this.departureDate = in.readString(this.departureDate instanceof Utf8 ? (Utf8)this.departureDate : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.waybillNum = in.readString(this.waybillNum instanceof Utf8 ? (Utf8)this.waybillNum : null);
          break;

        case 1:
          this.departureDate = in.readString(this.departureDate instanceof Utf8 ? (Utf8)this.departureDate : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










